# Generated by Django 4.2.3 on 2024-02-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_is_sales_product_sale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sales',
            new_name='is_sale',
        ),
    ]
